## [作業重點]
使用 Sklearn 中的 Lasso, Ridge 模型，來訓練各種資料集，務必了解送進去模型訓練的**資料型態**為何，也請了解模型中各項參數的意義。

機器學習的模型非常多種，但要訓練的資料多半有固定的格式，確保你了解訓練資料的格式為何，這樣在應用新模型時，就能夠最快的上手開始訓練！

## 練習時間
試著使用 sklearn datasets 的其他資料集 (boston, ...)，來訓練自己的線性迴歸模型，並加上適當的正則話來觀察訓練情形。

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets, linear_model
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

In [2]:
# 讀取 Boston 資料集
boston = datasets.load_boston()
#print (boston.data, boston.target)
# 切分訓練集/測試集
x_train, x_test, y_train, y_test = train_test_split(boston.data, boston.target, test_size=0.2, random_state=4)

# 建立一個線性回歸模型
regr = linear_model.LinearRegression()

# 將訓練資料丟進去模型訓練
regr.fit(x_train, y_train)

# 將測試資料丟進模型得到預測結果
y_pred = regr.predict(x_test)
print (regr.coef_)
MSE=mean_squared_error(y_test, y_pred)
R2 = r2_score(y_test, y_pred)
print ("MSE=", MSE, 'R2', R2)

[-1.15966452e-01  4.71249231e-02  8.25980146e-03  3.23404531e+00
 -1.66865890e+01  3.88410651e+00 -1.08974442e-02 -1.54129540e+00
  2.93208309e-01 -1.34059383e-02 -9.06296429e-01  8.80823439e-03
 -4.57723846e-01]
MSE= 25.41958712682191 R2 0.7263451459702503


Lasso

In [3]:
lasso = linear_model.Lasso(alpha = 1.0)
lasso.fit(x_train, y_train)
y_pred = lasso.predict (x_test)
print (lasso.coef_)
MSE=mean_squared_error(y_test, y_pred)
R2 = r2_score(y_test, y_pred)
print ("MSE=", MSE, 'R2', R2)

[-0.06494981  0.04581458 -0.          0.         -0.          1.18140024
  0.01109101 -0.73695809  0.23350042 -0.01551065 -0.69270805  0.00763157
 -0.6927848 ]
MSE= 28.95051203673903 R2 0.6883329337343633


Ridge Regression

In [4]:
ridge = linear_model.Ridge(alpha = 1.0)
ridge.fit(x_train, y_train)
y_pred = ridge.predict (x_test)
print (ridge.coef_)
MSE=mean_squared_error(y_test, y_pred)
R2 = r2_score(y_test, y_pred)
print ("MSE=", MSE, 'R2', R2)

[-1.12499445e-01  4.79562332e-02 -2.40438147e-02  2.96199458e+00
 -9.33966118e+00  3.93079015e+00 -1.73821202e-02 -1.43347691e+00
  2.75239392e-01 -1.38920708e-02 -8.31116943e-01  9.15637729e-03
 -4.66460539e-01]
MSE= 25.7436840800126 R2 0.7228560765383042


In [5]:
# 讀取 Wine 資料集
linnerud = datasets.load_linnerud()
#print (linnerud.data, linnerud.target)
# 切分訓練集/測試集
x_train, x_test, y_train, y_test = train_test_split(linnerud.data, linnerud.target, test_size=0.2, random_state=4)

# 建立一個線性回歸模型
regr = linear_model.LinearRegression()

# 將訓練資料丟進去模型訓練
regr.fit(x_train, y_train)

# 將測試資料丟進模型得到預測結果
y_pred = regr.predict(x_test)
print (regr.coef_)
MSE=mean_squared_error(y_test, y_pred)
R2 = r2_score(y_test, y_pred)
print ("MSE=", MSE, 'R2', R2)

[[-1.28756417 -0.18005567  0.0724611 ]
 [-0.23553638 -0.03945105  0.03009547]
 [ 0.17356644  0.05247911 -0.03166777]]
MSE= 386.1516447412519 R2 -0.9792083433421598


In [6]:
print ("y_pred=", y_pred)

y_pred= [[195.6971661   37.84182482  52.86554281]
 [183.28703617  35.50314354  54.52881826]
 [160.42626304  31.14584476  60.20697118]
 [189.22997661  36.63318872  53.59296829]]


Lasso

In [7]:
lasso = linear_model.Lasso(alpha = 1.0)
lasso.fit(x_train, y_train)
y_pred = lasso.predict (x_test)
print (lasso.coef_)
MSE=mean_squared_error(y_test, y_pred)
R2 = r2_score(y_test, y_pred)
print ("MSE=", MSE, 'R2', R2)

[[-1.21702413 -0.18301572  0.07085454]
 [-0.16500267 -0.04240416  0.02848377]
 [ 0.10302969  0.05543243 -0.03005608]]
MSE= 382.8840388945849 R2 -0.8829696112520873


Ridge Regression

In [8]:
ridge = linear_model.Ridge(alpha = 1.0)
ridge.fit(x_train, y_train)
y_pred = ridge.predict (x_test)
print (ridge.coef_)
MSE=mean_squared_error(y_test, y_pred)
R2 = r2_score(y_test, y_pred)
print ("MSE=", MSE, 'R2', R2)

[[-1.28169016 -0.18036401  0.072403  ]
 [-0.23446277 -0.03950683  0.03008403]
 [ 0.17278069  0.05251903 -0.03165848]]
MSE= 385.9336740736703 R2 -0.9775633066590993
